### ISSUE TITLE
camera button hides the system prompt window

### ISSUE THREAD

**Issue by kai-wng-uos** [virtUOS/kiwi#38] opened 2024-06-10 11:15 UTC
the toggle switch for turning camera access on/off overlays the window for the system prompt. Maybe it would make sense to move the button(s) down and attatch them to the chat input rather than the system prompt.
![grafik](https://github.com/virtUOS/kiwi/assets/152959695/e191721b-6b73-46d5-b04a-42226f30e635)
![grafik](https://github.com/virtUOS/kiwi/assets/152959695/efc37c6a-a157-43e2-9e27-ed0346c06484)

**Comment by kai-wng-uos** [comment] 2024-06-11 07:43
This seems to be an issue only in some browsers. Opera works for me, but using firefox the icon no overlays the info box on the top.
![grafik](https://github.com/virtUOS/kiwi/assets/152959695/624a0710-8bee-4d57-b7db-7fc271b7b14b)

**Comment by Odrec** [comment] 2024-06-11 07:54
Until now I haven't been able to reproduce this. This is what I see in Firefox.

![Screenshot from 2024-06-11 09-51-52](https://github.com/virtUOS/kiwi/assets/9385209/d79cb9b0-8345-42cc-8e0c-ead26796bbd3)

The only thing I can think of right now without seeing this issue myself is that Streamlit says in their documents to keep the browsers updated because there could be incompatibilities with older versions. Is your Firefox in the last version?

**Comment by Odrec** [comment] 2024-06-11 08:06
Is this in the Desktop browser?

**Comment by kai-wng-uos** [comment] 2024-06-11 08:14
yep

**Comment by Odrec** [comment] 2024-06-11 08:21
If there's anyone else that can reproduce this on Firefox or another browser, please let us know here.

**Comment by Odrec** [comment] 2024-07-03 08:34
This hasn't happened again apparently so I'm going to close it.

**Closed by Odrec** 2024-07-03 08:34 UTC
